name: Pull Request - build and run tests

on:
  push:
    branches:
      - master
      - development
  pull_request:
    branches:
      - master
      - development

env:
  FOUNDRY_PROFILE: ci
  CHAPEL_RPC: https://data-seed-prebsc-1-s1.binance.org:8545/
  MUMBAI_RPC: https://rpc.ankr.com/polygon_mumbai
  ARBI_GOERLI_RPC: https://goerli-rollup.arbitrum.io/rpc

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Npm dependencies
        run: yarn install

      - name: Install Npm dependencies
        run: yarn build

      - name: Lint Contracts
        run: yarn lint

      - name: Lint TS
        run: yarn lint-ts

  check:
    needs: [lint]
    strategy:
      fail-fast: true

    name: Run forge tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
